name: flutter_template
description: Flutter template for my projects.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  intl: ^0.20.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
