name: flutter_template
description: Flutter template for my projects.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.3.0
  go_router: ^17.2.3
  google_fonts: ^8.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
 
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

   
